#!/usr/bin/env bash
# ============================================================
# Bootstrap prérequis système (exemple lab)
#
# Usage :
#   sudo ./scripts/bootstrap-prereqs.sh
#
# Objectif :
#   - Installer Docker Engine + Docker Compose plugin
#   - Installer les utilitaires utiles au lab (curl, htpasswd, dig, jq...)
#   - Activer et démarrer Docker
#   - Ajouter l'utilisateur courant au groupe docker
#
# Distros prises en charge :
#   - Ubuntu / Debian
#   - Fedora / RHEL / Rocky / AlmaLinux
#   - Arch Linux
# ============================================================

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SUDO_USER_NAME="${SUDO_USER:-${USER:-}}"

log_info()    { echo -e "${BLUE}[INFO]${NC}  $*"; }
log_success() { echo -e "${GREEN}[OK]${NC}    $*"; }
log_warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
log_error()   { echo -e "${RED}[ERROR]${NC} $*" >&2; }

require_root() {
  if [[ "${EUID}" -ne 0 ]]; then
    log_error "Ce script doit etre execute en root (sudo)."
    exit 1
  fi
}

read_os_release() {
  if [[ ! -f /etc/os-release ]]; then
    log_error "Impossible de detecter la distribution (fichier /etc/os-release absent)."
    exit 1
  fi

  # shellcheck disable=SC1091
  source /etc/os-release
  OS_ID="${ID:-unknown}"
  OS_LIKE="${ID_LIKE:-}"
  OS_VERSION_CODENAME="${VERSION_CODENAME:-}"

  log_info "Distribution detectee : ${PRETTY_NAME:-${OS_ID}}"
}

ensure_common_tools() {
  log_info "Installation des outils communs..."

  case "${OS_ID}" in
    ubuntu|debian)
      apt-get update -y
      apt-get install -y ca-certificates curl gnupg lsb-release jq iproute2 git apache2-utils dnsutils
      ;;
    fedora|rhel|rocky|almalinux|centos)
      if command -v dnf >/dev/null 2>&1; then
        dnf -y install ca-certificates curl gnupg2 jq iproute git httpd-tools bind-utils
      else
        yum -y install ca-certificates curl gnupg2 jq iproute git httpd-tools bind-utils
      fi
      ;;
    arch)
      pacman -Sy --noconfirm ca-certificates curl gnupg jq iproute2 git apache
      ;;
    *)
      log_warn "Distribution non supportee nativement pour les outils communs."
      ;;
  esac

  log_success "Outils communs installes."
}

install_docker_debian_family() {
  log_info "Installation de Docker (Ubuntu/Debian)..."

  install -m 0755 -d /etc/apt/keyrings
  if [[ ! -f /etc/apt/keyrings/docker.asc ]]; then
    curl -fsSL https://download.docker.com/linux/${OS_ID}/gpg -o /etc/apt/keyrings/docker.asc
    chmod a+r /etc/apt/keyrings/docker.asc
  fi

  if [[ -z "${OS_VERSION_CODENAME}" ]]; then
    OS_VERSION_CODENAME="$(. /etc/os-release && echo "${VERSION_CODENAME:-}")"
  fi

  cat >/etc/apt/sources.list.d/docker.list <<EOF
# Docker official repository
# Generated by lab bootstrap script
deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/${OS_ID} ${OS_VERSION_CODENAME} stable
EOF

  apt-get update -y
  apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

  log_success "Docker et Compose plugin installes."
}

install_docker_rhel_family() {
  log_info "Installation de Docker (Fedora/RHEL family)..."

  if command -v dnf >/dev/null 2>&1; then
    dnf -y install dnf-plugins-core
    dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo || true
    dnf -y install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  else
    yum -y install yum-utils
    yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo || true
    yum -y install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  fi

  log_success "Docker et Compose plugin installes."
}

install_docker_arch() {
  log_info "Installation de Docker (Arch Linux)..."
  pacman -Sy --noconfirm docker docker-compose
  log_success "Docker et docker-compose installes."
}

install_or_validate_docker() {
  if command -v docker >/dev/null 2>&1 && (docker compose version >/dev/null 2>&1 || command -v docker-compose >/dev/null 2>&1); then
    log_success "Docker et Compose deja presents."
    return
  fi

  case "${OS_ID}" in
    ubuntu|debian)
      install_docker_debian_family
      ;;
    fedora|rhel|rocky|almalinux|centos)
      install_docker_rhel_family
      ;;
    arch)
      install_docker_arch
      ;;
    *)
      if [[ "${OS_LIKE}" == *"debian"* ]]; then
        OS_ID="debian"
        install_docker_debian_family
      elif [[ "${OS_LIKE}" == *"rhel"* || "${OS_LIKE}" == *"fedora"* ]]; then
        OS_ID="fedora"
        install_docker_rhel_family
      else
        log_error "Distribution non supportee automatiquement pour Docker."
        log_error "Installe Docker manuellement puis relance le script d'installation du lab."
        exit 1
      fi
      ;;
  esac
}

enable_docker_service() {
  log_info "Activation du service Docker..."
  systemctl enable --now docker
  log_success "Service Docker actif."
}

configure_docker_group() {
  if ! getent group docker >/dev/null; then
    groupadd docker
  fi

  if [[ -n "${SUDO_USER_NAME}" && "${SUDO_USER_NAME}" != "root" ]]; then
    usermod -aG docker "${SUDO_USER_NAME}" || true
    log_success "Utilisateur ${SUDO_USER_NAME} ajoute au groupe docker."
    log_warn "Deconnecte-toi/reconnecte-toi pour prendre en compte le groupe docker."
  else
    log_warn "Utilisateur non detecte pour ajout au groupe docker (execution en root direct)."
  fi
}

print_versions() {
  log_info "Versions detectees :"
  docker --version || true
  docker compose version || docker-compose --version || true
  curl --version | head -1 || true
  jq --version || true
  if command -v dig >/dev/null 2>&1; then
    dig -v | head -1 || true
  fi
}

print_next_steps() {
  echo ""
  echo "Prérequis système installés."
  echo "Passez à la génération du fichier .env et à l'installation du lab."
  echo "Consultez le README ou lancez ./scripts/generate-env.sh pour continuer."
  echo ""
}

main() {
  require_root
  read_os_release
  ensure_common_tools
  install_or_validate_docker
  enable_docker_service
  configure_docker_group
  print_versions
  print_next_steps
  log_success "Bootstrap des prerequis termine."
}

main "$@"
